[package]
edition = "2024"
name    = "crypto"
version = "0.1.0"

[dependencies]
anyhow.workspace = true
blst             = "0.3.16"
blake3.workspace = true
hex.workspace    = true
rand.workspace   = true
rkyv.workspace   = true
